"""book table

Revision ID: 901821a6561b
Revises: 
Create Date: 2019-02-05 17:30:14.479215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901821a6561b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
